[project]
name = "kb-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "janus-swi>=1.5.2",
    "pyswip>=0.3.3",
    "python-dotenv>=1.1.1",
    "z3-solver>=4.15.3.0",
]
