[project]
name = "kb-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.107.0",
    "openai-agents>=0.2.11",
    "pydantic>=2.11.7",
    "pyswip>=0.3.3",
    "python-dotenv>=1.1.1",
]
